=== maheshv18/ECommerce/XML/V0/product_type.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (productID, oname, phone, address, date, product1,amount)>
<!ELEMENT product1 (sproduct+)>
<!ELEMENT sproduct (product_name, quantity, discount)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT discount (#PCDATA)>
<!ELEMENT productID (#PCDATA)>
<!ELEMENT oname (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== maheshv18/ECommerce/XML/product_ordered.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE products SYSTEM "product_type.dtd">
<products>
    <product>
        <productID>101</productID>
        <oname>Mahesh</oname>
        <phone>6384803545</phone>
        <address>Ettimadai, Coimbatore</address>
        <date>25/08/2022</date>
        <product>
            <sproduct>
                <product_name>Mobile</product_name>
                <quantity>1</quantity>
                <discount>$1000</discount>
            </sproduct>
            <sproduct>
                <product_name>Laptop</product_name>
                <quantity>1</quantity>
                <discount>$1500</discount>
            </sproduct>
        </product>
        <amount>2500</amount>
    </product>
</products>
