=== maheshv18/ECommerce/XML/order_type.dtd
<!ELEMENT orders (order+)>
<!ELEMENT order (orderID, oname, phone, address, date, products,amount)>
<!ELEMENT products (product+)>
<!ELEMENT product (product_name, quantity, discount)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT discount (#PCDATA)>
<!ELEMENT orderID (#PCDATA)>
<!ELEMENT oname (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== maheshv18/ECommerce/XML/orders.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE orders SYSTEM "order_type.dtd">
<orders>
    <order>
        <orderID>101</orderID>
        <oname>Mahesh</oname>
        <phone>6384803545</phone>
        <address>Ettimadai, Coimbatore</address>
        <date>25/08/2022</date>
        <products>
            <product>
                <product_name>Mobile</product_name>
                <quantity>1</quantity>
                <discount>$1000</discount>
            </product>
            <product>
                <product_name>Laptop</product_name>
                <quantity>1</quantity>
                <discount>$1500</discount>
            </product>
        </products>
        <amount>2500</amount>
    </order>
</orders>
