=== maheshv18/ECommerce/XML/signup.xsd
<?xml version="1.0"?>  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.signup.com"
xmlns="http://www.signup.com"
elementFormDefault="qualified">
<xs:element name="SignUp">  
  <xs:complexType>
    <xs:sequence>
        <xs:element name="User"  minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                    <xs:element name="Name">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[0-9a-zA-Z_ ]{3,}"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Email">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+"></xs:pattern>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Phone" >
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:pattern value="[1-9][0-9]{9}"></xs:pattern>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Password">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[A-Za-z0-9#?!@$%^*-].{6,}"></xs:pattern>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="ConfirmPassword">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[A-Za-z0-9#?!@$%^*-].{6,}"></xs:pattern>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                </xs:all>
                <xs:attribute name="id" type="xs:ID"/>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>   
</xs:schema>

=== maheshv18/ECommerce/XML/signup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- IMPLICIT DTD -->
<!DOCTYPE SignUp [
<!ELEMENT SignUp (User+)>
<!ELEMENT User (Name,Email,Phone,Password,ConfirmPassword)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT ConfirmPassword (#PCDATA)>
<!ATTLIST User id ID (#REQUIRED)>
]>
<!-- 
EXPLICIT DTD
<!DOCTYPE SignUp SYSTEM "signup.dtd"> 
-->
<SignUp xmlns="http://www.signup.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.signup.com signup.xsd">
    <User id="maheshv123">
        <Name>Mahesh</Name>
        <Email>Mahesh23042002@gmail.com</Email>
        <Phone>6384803545</Phone>
        <Password>Password123</Password>
        <ConfirmPassword>Password123</ConfirmPassword>
    </User>
    <User id="mahsh123">
        <Name>Mahesh1</Name>
        <Email>Mahesh1l123@gmail.com</Email>
        <Phone>6384803548</Phone>
        <Password>Password012</Password>
        <ConfirmPassword>Password012</ConfirmPassword>
    </User>
    <User id="vishal12345">
        <Name>Mahesh2</Name>
        <Email>vishal12345@gmail.com</Email>
        <Phone>4353455435</Phone>
        <Password>PassWord</Password>
        <ConfirmPassword>PassWord</ConfirmPassword>
    </User>
</SignUp>
